### ISSUE TITLE
The meaning of num_mix

### ISSUE THREAD

**Issue by developer0hye** [ildoonet/cutmix#4]
https://github.com/ildoonet/cutmix/blob/055e91151edb6d079b98f453f7e7553ed4ccbb3f/cutmix/cutmix.py#L20

Thank you for sharing great works!

I have a question. What's the meaning of num_mix?

Is it the maximum number of mixed class?

**Comment by ildoonet** [comment]
@developer0hye 

It is an experimental parameter, which mixes multiple images more than just two.

If you use num_mix=2, then it will mixes two images into the original image. 

The default value is 1, as the original paper.

**Comment by developer0hye** [comment]
@ildoonet 
Thanks!
